/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f411xe.h>
#include "systick.h"
#include "gpio.h"
#include "spi.h"
#include "mux.h"
#include "display.h"
#include "render.h"
#include "assets/icons/icons.h"
#include "i2c.h"
#include "hdc2022.h"
#include "mcp7940.h"
#include "clockface.h"
#include "statemachine.h"
#include "timeanddate.h"
#include "timer.h"
#include "alarms.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void init_clocks();
void enable_module_clocks();
uint8_t button_status = 0;
uint8_t event_occurred=0;


int main(void)
{
	init_clocks();
	enable_module_clocks();
	init_systick();
	start_systick();
	init_mux();
	init_gpio();
	init_spi1();
	i2c_init();
	display_init();
	init_mcp7940();
	init_fonts();

	timer4_init();
	timer5_init();

	__enable_irq();
	assemble_clockface();
	display_render_image((uint8_t *)image_buffer);
	display_init_partial();
	while(1){
		update_time();
		if(check_time_diff()){
			update_clockface = 1;
		}
		button_status = get_button_status();

		if( (is_alarm_ringing()) && button_status == 1)
		{
			button_status = 0;
		}
		if(event_occurred){
			event_occurred = 0;
			process_event(button_status);
		}
		clockface_update();
		if(display_timeout_flag){
			update_clockface = 1;
			init_gpio();
			display_init();
			clockface_update();
			display_init_partial();
			display_timeout_flag = 0;
		}
		check_alarm_match();
	}

}
void init_clocks(){

		RCC->CR	&= ~(RCC_CR_PLLON);
		RCC->CFGR |= (0b11<< RCC_CFGR_MCO1_Pos);
		FLASH->ACR = (1<<8) | (1<<9)| (1<<10)| (5<<0);
		RCC->PLLCFGR = 0;
		RCC->PLLCFGR |= (8<<RCC_PLLCFGR_PLLQ_Pos)|(8<<RCC_PLLCFGR_PLLM_Pos)|(192<<RCC_PLLCFGR_PLLN_Pos)|(1<<RCC_PLLCFGR_PLLP_Pos);
		RCC->CR |= RCC_CR_HSION;
		while(!( RCC->CR & RCC_CR_HSIRDY));
		RCC->CFGR |= (0b100<<RCC_CFGR_PPRE1_Pos)|(0b000<<RCC_CFGR_PPRE2_Pos)|(0b0000<<RCC_CFGR_HPRE_Pos);
		RCC->CR |= RCC_CR_PLLON;
		while(!( RCC->CR & RCC_CR_PLLRDY));
		RCC->CFGR |= (0b10<<RCC_CFGR_SW_Pos);
		while(!(RCC->CFGR & RCC_CFGR_SWS_PLL));
}
void enable_module_clocks(){
	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOAEN); 	// GPIO A
	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOBEN); 	//GPIO B
	RCC->APB2ENR |= RCC_APB2ENR_SPI1EN; 	// SPI1
	RCC->APB1ENR |= RCC_APB1ENR_I2C1EN; 	// I2C1
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN; 	// GPIOD
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;		// TIMER4;
	RCC->APB1ENR |= RCC_APB1ENR_TIM5EN;		// TIMER4;
}
