/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f411xe.h>
#include "systick.h"
#include "gpio.h"
#include "spi.h"
#include "mux.h"
#include "display.h"
#include "render.h"
#include "i2c.h"
#include "hdc2022.h"
#include "mcp7940.h"
#include "clockface.h"
#include "statemachine.h"
#include "timeanddate.h"
#include "timer.h"
#include "clocks.h"
#include "alarms.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t button_status = 0;
uint8_t event_occurred=0;


int main(void)
{
	init_clocks();
	enable_module_clocks();
	init_systick();
	start_systick();
	init_mux();
	init_gpio();
	init_spi1();
	i2c_init();
	timer4_init();
	timer5_init();


	init_mcp7940();
	init_fonts();



	assemble_clockface();
	display_init();
	display_render_image((uint8_t *)image_buffer);
	display_init_partial();
	__enable_irq();
	while(1){
		update_time();
		if(check_time_diff()){
			update_clockface = 1;
		}
		button_status = get_button_status();

		if( (is_alarm_ringing()) && button_status == 1)
		{
			button_status = 0;
		}
		if(event_occurred){
			event_occurred = 0;
			process_event(button_status);
		}
		clockface_update();
		if(display_timeout_flag){ // Resets the display in case of a busy wait timeout.
			update_clockface = 1;
			init_gpio();
			display_init();
			clockface_update();
			display_init_partial();
			display_timeout_flag = 0;
		}
		check_alarm_match();
	}

}

