/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f411xe.h>
#include "systick.h"
#include "gpio.h"
#include "spi.h"
#include "mux.h"
#include "display.h"
#include "render.h"
#include "assets/icons/icons.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void init_clocks();
void enable_module_clocks();
extern const unsigned char gImage_4in2[];
int main(void)
{
//	init_clocks();
	enable_module_clocks();
	init_mux();
	init_gpio();
	init_spi1();
	init_systick();
	start_systick();
	display_init();
	init_draw_module();
	init_fonts();
	draw_string("0 9 : 2 4", COOLVETICACR200, BLACK, 45, 290);
	draw_string("11, December 2023", HELVETICA30, BLACK, 0, 48);
	draw_image(weather_icons, 230, 54, 48, 48);
	draw_hLine(0, 60, 399, BLACK);
	draw_vLine(300, 0, 299, BLACK);
	display_render_image((uint8_t *)image_buffer);
	delay_ms(5000);
	display_clear();
    /* Loop forever */
	for(;;);
}
void init_clocks(){

		RCC->CR	&= ~(RCC_CR_PLLON);
		RCC->CFGR |= (0b11<< RCC_CFGR_MCO1_Pos);
		FLASH->ACR = (1<<8) | (1<<9)| (1<<10)| (5<<0);
		RCC->PLLCFGR = 0;
		RCC->PLLCFGR |= (8<<RCC_PLLCFGR_PLLQ_Pos)|(8<<RCC_PLLCFGR_PLLM_Pos)|(192<<RCC_PLLCFGR_PLLN_Pos)|(1<<RCC_PLLCFGR_PLLP_Pos);
		RCC->CR |= RCC_CR_HSION;
		while(!( RCC->CR & RCC_CR_HSIRDY));
		RCC->CFGR |= (0b100<<RCC_CFGR_PPRE1_Pos)|(0b000<<RCC_CFGR_PPRE2_Pos)|(0b0000<<RCC_CFGR_HPRE_Pos);
		RCC->CR |= RCC_CR_PLLON;
		while(!( RCC->CR & RCC_CR_PLLRDY));
		RCC->CFGR |= (0b10<<RCC_CFGR_SW_Pos);
		while(!(RCC->CFGR & RCC_CFGR_SWS_PLL));
}
void enable_module_clocks(){
	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOAEN); // GPIO A
	RCC->APB2ENR |= RCC_APB2ENR_SPI1EN; // SPI1
}
